package hidroponiksahabat;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.ChartFrame;

public class Home extends javax.swing.JFrame {
    Map<String, String> date;
    Map<String, Integer> barang;
    public Home() {
        initComponents();
        setGrafik();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonStok = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        ButtonGanti = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        background1 = new hidroponiksahabat.Background();
        jButtonMin = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 580, 10));

        ButtonStok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonStok.setText("Cek Stok");
        ButtonStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStokActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 302, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("+ Transaksi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 302, -1, -1));

        ButtonLogout.setBackground(new java.awt.Color(255, 0, 0));
        ButtonLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogout.setText("Logout");
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        ButtonGanti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonGanti.setText("Ganti Password");
        ButtonGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGantiActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonGanti, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 302, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 114, 168));

        background1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonMin.setBackground(new java.awt.Color(16, 203, 22));
        jButtonMin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonMin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMin.setText("—");
        jButtonMin.setFocusable(false);
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });

        jButtonClose.setBackground(new java.awt.Color(255, 0, 0));
        jButtonClose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClose.setText("X");
        jButtonClose.setFocusable(false);
        jButtonClose.setMaximumSize(new java.awt.Dimension(49, 31));
        jButtonClose.setMinimumSize(new java.awt.Dimension(49, 31));
        jButtonClose.setPreferredSize(new java.awt.Dimension(49, 31));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Grafik Penjualan");

        jButton1.setText("Tampilkan Grafik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Bulan dan Tahun");

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addComponent(jButtonMin)
                .addGap(0, 0, 0)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMin)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStokActionPerformed
        this.setVisible(false);
                new CekStok().setVisible(true);
    }//GEN-LAST:event_ButtonStokActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Anda Yakin Logout?", "Yakin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
                new formLogin().setVisible(true);
        }
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButtonMinActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void ButtonGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGantiActionPerformed
        this.setVisible(false);
        new GantiPassword().setVisible(true);
    }//GEN-LAST:event_ButtonGantiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String terpilih = jComboBox4.getSelectedItem().toString();
        String data = date.get(terpilih).toString();
        barang = new HashMap<>();
        try{
              Statement stat = (Statement) koneksi.koneksiDB().createStatement();
              String sql = "select transaksi.id_transaksi, tanggal_transaksi, barang.id_barang, barang.nama_barang, item_transaksi.jumlah_barang "
                      + "from transaksi inner join item_transaksi on transaksi.id_transaksi = item_transaksi.id_transaksi "
                      + "inner join barang on item_transaksi.id_barang = barang.id_barang;";
              ResultSet res = stat.executeQuery(sql);

              while(res.next ()){
                    if(res.getString(2).startsWith(data)){
                        if(barang.containsKey(res.getString(3))){
                            barang.replace(res.getString(3), barang.get(res.getString(3))+ res.getInt(4));
                        }else{
                            barang.put(res.getString("nama_barang"), res.getInt("jumlah_barang"));
                        }
                    }
               }
              DefaultPieDataset object = new DefaultPieDataset();
              for (Map.Entry m:barang.entrySet()){
                object.setValue((Comparable) m.getKey(), (Integer)m.getValue());
            }
              JFreeChart chart = ChartFactory.createPieChart("Pie Chart", object);
              ChartFrame frame = new ChartFrame("Grafik Penjualan pada" + terpilih, chart);
              frame.setSize(400, 400);
              frame.setVisible(true);
         }catch(SQLException err){
               JOptionPane.showMessageDialog(null, err.getMessage() );
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed
    
    private void setGrafik(){
        try {
            ArrayList<String> tanggal = new ArrayList<String>();
            date = new HashMap<String, String>();
            Statement stat = (Statement) koneksi.koneksiDB().createStatement();
            String sql = "Select * from transaksi";
            ResultSet res = stat.executeQuery(sql);

            while (res.next()) {
                tanggal.add(res.getString(2));
            }
            for(String data: tanggal){
                String test = data.substring(5, 7);
                switch(test){
                    case "01" : 
                        date.put("Januari " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "02":
                        date.put("Februari " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "03" : 
                        date.put("Maret " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "04":
                        date.put("April " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "05" : 
                        date.put("Mei " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "06":
                        date.put("Juni " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "07" : 
                        date.put("Juli " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "08":
                        date.put("Agustus " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "09" : 
                        date.put("September " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "10":
                        date.put("Oktober " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "11" : 
                        date.put("November " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                    case "12":
                        date.put("Desember " + data.substring(0, 4), (String) data.subSequence(0, 7));
                        break;
                }
                jComboBox4.removeAllItems();
            for (Map.Entry m:date.entrySet()){
                jComboBox4.addItem(m.getKey());
            }
            }
                
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonGanti;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonStok;
    private hidroponiksahabat.Background background1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
